# Generated by Django 5.2.4 on 2025-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_sendtocrm_data_sendtocrm_apikey_sendtocrm_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtosi',
            name='SI_Template',
            field=models.JSONField(default='def'),
            preserve_default=False,
        ),
    ]
