# Generated by Django 5.2.4 on 2025-12-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_sendtosi_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtosi',
            name='Closing_Date',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
