# Generated by Django 5.2.4 on 2025-12-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sendtosi_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendtosi',
            name='Engineering_Lead',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Owner',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendtosi',
            name='Project_Manager',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
